require("plugins.packer")

require("plugins.cmp")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.nvim-tree")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.luasnip")
require("plugins.toggleterm")
require("plugins.project")
require("plugins.navigator")
require("plugins.colorizer")
require("plugins.crates")
-- require("plugins.rzip")
require("plugins.diffview")
require("plugins.todo")
require("plugins.octo")
require("plugins.trouble")
require("plugins.cheatsheet")
require("plugins.neoclip")
